# 📌 Extracción

In [32]:
import pandas as pd
import requests
import json

In [33]:
url = "https://raw.githubusercontent.com/ingridcristh/challenge2-data-science-LATAM/main/TelecomX_Data.json"

In [36]:
try:
    response = requests.get(url)
    data = response.json()
    
    df = pd.DataFrame(data)
    
    print("Extracción exitosa")
except Exception as e:
    print(f"Error en la extracción: {e}")

Extracción exitosa

In [37]:
df.head()

,customerID,Churn,customer,phone,internet,account
0,0002-ORFBO,No,"{'gender': 'Female', 'SeniorCitizen': 0, 'Part...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'DSL', 'OnlineSecurity': '...","{'Contract': 'One year', 'PaperlessBilling': '..."
1,0003-MKNFE,No,"{'gender': 'Male', 'SeniorCitizen': 0, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'Yes'}","{'InternetService': 'DSL', 'OnlineSecurity': '...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
2,0004-TLHLJ,Yes,"{'gender': 'Male', 'SeniorCitizen': 0, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'Fiber optic', 'OnlineSecu...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
3,0011-IGKFF,Yes,"{'gender': 'Male', 'SeniorCitizen': 1, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'Fiber optic', 'OnlineSecu...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
4,0013-EXCHZ,Yes,"{'gender': 'Female', 'SeniorCitizen': 1, 'Part...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'Fiber optic', 'OnlineSecu...","{'Contract': 'Month-to-month', 'PaperlessBilli..."

# 🔧 Transformación

In [38]:
df_customer = pd.json_normalize(df['customer'])
df_phone = pd.json_normalize(df['phone'])
df_internet = pd.json_normalize(df['internet'])
df_account = pd.json_normalize(df['account'])

In [39]:
df_final = pd.concat([df[['customerID', 'Churn']], df_customer, df_phone, df_internet, df_account], axis=1)

In [40]:
columnas = {
    'customerID': 'ID_Cliente', 'Churn': 'Evasion', 'gender': 'Genero', 
    'SeniorCitizen': 'Adulto_Mayor', 'Partner': 'Socio', 'Dependents': 'Dependientes',
    'tenure': 'Meses_Permanencia', 'PhoneService': 'Servicio_Telefono', 
    'MultipleLines': 'Lineas_Multiples', 'InternetService': 'Servicio_Internet', 
    'OnlineSecurity': 'Seguridad_Online', 'OnlineBackup': 'Respaldo_Online', 
    'DeviceProtection': 'Proteccion_Dispositivo', 'TechSupport': 'Soporte_Tecnico', 
    'StreamingTV': 'Streaming_TV', 'StreamingMovies': 'Streaming_Peliculas', 
    'Contract': 'Contrato', 'PaperlessBilling': 'Facturacion_Electronica', 
    'PaymentMethod': 'Metodo_Pago', 'Charges.Monthly': 'Cargos_Mensuales', 
    'Charges.Total': 'Cargos_Totales'
}
df_final.rename(columns=columnas, inplace=True)

In [41]:
df_final['Cargos_Totales'] = pd.to_numeric(df_final['Cargos_Totales'], errors='coerce')
df_final['Cuentas_Diarias'] = (df_final['Cargos_Mensuales'] / 30).round(2)

In [42]:
df_final.head()

,ID_Cliente,Evasion,Genero,Adulto_Mayor,Socio,Dependientes,Meses_Permanencia,Servicio_Telefono,Lineas_Multiples,Servicio_Internet,...,Proteccion_Dispositivo,Soporte_Tecnico,Streaming_TV,Streaming_Peliculas,Contrato,Facturacion_Electronica,Metodo_Pago,Cargos_Mensuales,Cargos_Totales,Cuentas_Diarias
0,0002-ORFBO,No,Female,0,Yes,Yes,9,Yes,No,DSL,...,No,Yes,Yes,No,One year,Yes,Mailed check,65.6,593.30,2.19
1,0003-MKNFE,No,Male,0,No,No,9,Yes,Yes,DSL,...,No,No,No,Yes,Month-to-month,No,Mailed check,59.9,542.40,2.00
2,0004-TLHLJ,Yes,Male,0,No,No,4,Yes,No,Fiber optic,...,Yes,No,No,No,Month-to-month,Yes,Electronic check,73.9,280.85,2.46
3,0011-IGKFF,Yes,Male,1,Yes,No,13,Yes,No,Fiber optic,...,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,98.0,1237.85,3.27
4,0013-EXCHZ,Yes,Female,1,Yes,No,3,Yes,No,Fiber optic,...,No,Yes,Yes,No,Month-to-month,Yes,Mailed check,83.9,267.40,2.80

# 📊 Carga y análisis

# 📄Informe final